create table Engineer
(
    engineer_id       INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name        varchar(100) not null,
    last_name         varchar(100) not null,
    discipline        varchar(20)  not null,
    email             varchar(100) not null unique,
    telegram_username varchar(50) unique,
    username varchar unique,
    password varchar,
    role varchar
);

create table Project
(
    project_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name       varchar(200) not null unique
);

create table Collision
(
    collision_id   INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    project_id     INT REFERENCES Project (project_id) ON DELETE CASCADE,
    engineer_id    INT REFERENCES Engineer (engineer_id) ON DELETE SET NULL,
    discipline_1   varchar(20)  not null,
    discipline_2   varchar(20)  not null,
    element_name_1 varchar(200) not null,
    element_name_2 varchar(200) not null,
    element_id_1   varchar(20)          not null,
    element_id_2   varchar(20)          not null,
    status         varchar(20)  not null,
    comment        varchar(200),
    created_at     timestamp    not null,
    fake           boolean default false
);

create table Project_Engineer
(
    project_id  int REFERENCES Project (project_id),
    engineer_id int REFERENCES Engineer (engineer_id),
    PRIMARY KEY (project_id, engineer_id)
);

create table html_report (
    report_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    engineer_id INT REFERENCES Engineer (engineer_id) ON DELETE SET NULL,
    name varchar,
    uploaded_at timestamp,
    data varchar
)




